services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - go-food-tech-challenge-network

  server:
    build:
      context: .
    container_name: go_tech_challenge_customer_app
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      mongo:
        condition: service_started
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    networks:
      - go-food-tech-challenge-network

volumes:
  mongo_data:

networks:
  go-food-tech-challenge-network:
    driver: bridge
