// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	customer "github.com/pangolin-do-golang/tech-challenge-customer-api/internal/core/customer"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *IService) Create(_a0 customer.Customer) (*customer.Customer, error) {
	ret := _m.Called(_a0)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(customer.Customer) (*customer.Customer, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(customer.Customer) *customer.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(customer.Customer) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: customerId
func (_m *IService) Delete(customerId uuid.UUID) error {
	ret := _m.Called(customerId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(customerId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *IService) GetAll() ([]customer.Customer, error) {
	ret := _m.Called()

	var r0 []customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]customer.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []customer.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCpf provides a mock function with given fields: customerCpf
func (_m *IService) GetByCpf(customerCpf string) (*customer.Customer, error) {
	ret := _m.Called(customerCpf)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*customer.Customer, error)); ok {
		return rf(customerCpf)
	}
	if rf, ok := ret.Get(0).(func(string) *customer.Customer); ok {
		r0 = rf(customerCpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerCpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: customerId, _a1
func (_m *IService) Update(customerId uuid.UUID, _a1 customer.Customer) (*customer.Customer, error) {
	ret := _m.Called(customerId, _a1)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, customer.Customer) (*customer.Customer, error)); ok {
		return rf(customerId, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, customer.Customer) *customer.Customer); ok {
		r0 = rf(customerId, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, customer.Customer) error); ok {
		r1 = rf(customerId, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIService creates a new instance of IService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIService(t mockConstructorTestingTNewIService) *IService {
	mock := &IService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
